### PR TITLE
Upgrade to Jest v27

### PR DESCRIPTION
**Pull request by ZauberNerd**
This commit upgrades the project to Jest v27.
The `config` argument to the `Transformer.process()` method has been
moved into the `TransformOptions`.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Anything we can do to get this merged and released @aelbore?

**Comment by wmertens** [comment]
I'm using this with jest 28 and not encountering any issues, so I suppose this can be closed?

EDIT: ah - I'm not sure if I'm using the `config` actually. I'm using this configuration, and it does honor the format option

```
	transform: {
		'^.+\\.[jt]sx?$': [
			'esbuild-jest',
			{sourcemap: true, target: 'node18', format: 'esm'},
		],
	},
```

**Comment by p0wl** [comment]
@aelbore what's missing here to get this merged?

**Comment by etroynov** [comment]
Fixed https://github.com/etroynov/esbuild-jest/pull/4

**Pull request closed without merging**
